### ISSUE TITLE
Not working in Qubes 4?

### ISSUE THREAD

**Issue by Mayeu** [rustybird/qubes-updates-cache#2]
Hello,

I'm a recent Qubes-OS user, and because of some issue making 3.2 not runnable on my laptop, I am using the 4.0-rc1 instead.

I tried to follow the instruction in the installation but without success (`qvm-create` does not have the `--proxy` option anymore, and the `qubes-updates-cache` service does not seem to exist).

Are you aware of this issue, or working to support Qubes 4?

Thank you for any help, I can also help with some debugging if needed :)

**Comment by rustybird** [comment]
> `qvm-create` does not have the `--proxy` option anymore

Yes, omit `--proxy` on R4.0.

> and the `qubes-updates-cache` service does not seem to exist

That's normal: The `qvm-service` command is intended to create and then enable the service. But its syntax has been changed slightly in R4.0. I've updated the README.

> Are you aware of this issue, or working to support Qubes 4?
>
> Thank you for any help, I can also help with some debugging if needed :)

So far, I haven't tested qubes-updates-cache on R4.0 at all. It would be interesting to see if it works when you install it like this:

  - After running `./install` on squidp, run `ln -sf /bin/true /usr/lib/qubes/updates-cache-iptables`.
  - Skip the two commands in the README's "Make your new ProxyVM the netvm..." section
  - In dom0's `/etc/qubes-rpc/policy/qubes.UpdatesProxy`, change `sys-net` to `squidp`.

**Comment by rustybird** [comment]
After running `./install`, also create a `/usr/lib/systemd/system/qubes-updates-proxy-forwarder.socket.d/r4.0.conf` file with the following contents:

    [Unit]
    ConditionPathExists=!/var/run/qubes-service/qubes-updates-cache

**Comment by Mayeu** [comment]
Thank you for all the details. I followed your guide and changes, but I am unable to make it work. As soon as I switch from sys-net to squid-update-vm in the `/etc/qubes-rpc/policy/qubes.UpdatesProxy`, I can't update my templates anymore:
```
$ sudo dnf upgrade
Error: Failed to synchronize cache for repo 'qubes-vm-r4.0-current'
```
is the `qubes-updates-proxy-forwarder` service supposed to be running? (it is not right now)

Thank you for your help.

**Comment by rustybird** [comment]
Sorry, it took me forever to get around to this. Feel free to reopen this issue if the current version does not work for you on Qubes R4.0.

**Comment by ben-grande** [comment]
Hello Rustybird, has qubes-updates-cache being tested on R4.2? I already use apt-cacher-ng, but if squid can give me zero problems with fedora and cache fedora packages, then I will evaluate it.

**Comment by rustybird** [comment]
@ben-grande:

Theoretically I don't see why not, but I haven't used or even tested it at all since R4.0.

These days you might have to edit the distributions' repository URLs inside your TemplateVMs to switch them from HTTPS to HTTP so that Squid can intercept the requests (and hopefully upgrade them to HTTPS itself - but it's possible that the [URL rewriting rules](https://github.com/rustybird/qubes-updates-cache/blob/master/etc/qubes-updates-cache/urls/30-default-rules.bash) would need to be brought up to date).
